from .templates import (
    CRITIC_SYSTEM_PROMPT,
    EDUBENCH_JSON_SYSTEM_PROMPT,
    TUTOR_SYSTEM_PROMPT,
    VISION_TUTOR_SYSTEM_PROMPT,
)

__all__ = [
    "CRITIC_SYSTEM_PROMPT",
    "EDUBENCH_JSON_SYSTEM_PROMPT",
    "TUTOR_SYSTEM_PROMPT",
    "VISION_TUTOR_SYSTEM_PROMPT",
]
